### ISSUE TITLE
App concept?

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_khomtali#1]
Hello @khomtali this is the repo for your final project and this issue a place to discuss you final project idea.

What is your app idea? What features will it have?

**Comment by khomtali** [comment]
Hello!
My idea is an app for configuration of jogging trainings' plan.
It offers at least 2 functions:
- to calculate approximate heart rate zones (possible without personal account)
- to configure training plan depending on different requirements (registration necessary)

Requirments to configure a training schedule are:
- experience in jogging or expected level of training intensity (3 levels)
- distance of target race (5, 10 km, half-marathon, marathon)
- and two options to choose: date of final race (with minimal period - not earlier as in 4 weeks, for example) or training frequency per week
- ...

In personal account one can:
- see the trainings plan in calender
- tick trainings as done
- change a day of trainings (with drag&drop)
- download trainings for google/apple calender (???)
- connect with Strava / NRC to download completed trainings (???)
- ...

And the main question is - where can I get different plans of trainings for free? Now I have only one resourse and that is a book, so in that case I need to build two data bases: one with different types of trainings and the second with different combinations of these trainings.
I was trying to find any other resource on internet, but so far haven't seen.

That's all my thoughts.

How do you find my idea? Do you think this is manageable for me?

**Comment by BTBTravis** [comment]
Hey @khomtali I like your concept. 

Could you walk me through the journey of your guest user?

Ex:
- Lands on site
- enters data??
- sees approx heart rate zones?

Also for the registered user

**Comment by BTBTravis** [comment]
Looking for running related APIs I found https://www.runningahead.com/#log_workouts

**Comment by BTBTravis** [comment]
Also found https://api.smashrun.com/

**Comment by BTBTravis** [comment]
Loosely related is Fitbit APIs https://dev.fitbit.com/getting-started/

**Comment by BTBTravis** [comment]
https://2peak.com/api/why.php has something to do with tracking trainings. 🤔

**Comment by BTBTravis** [comment]
strava seems to have a bunch of cool stuff in their APIs https://developers.strava.com/

**Comment by khomtali** [comment]
@BTBTravis, thank you for the links you found, I've already seen some of them. I try to sum up my thoughts about each a bit later.

The journey of guest user is absolutely not long, like as you wrote in example 🙃
That will be only one page devided by 2 parts - calculation of pulse zones and sign-up form. For pulse zones guest needs to enter only 2 parameters: resting heart rate (explanation how to measure will be given under a tooltip) and age. And after submission guest sees approximate heart rate zones and a suggestion to save results in his personal account.

After registration, in personal account will be 3 pages available:
- a page of personal running plans. There is a list of created plans, with name, type, progress bar. One can click on the plan to manage it, and it opens in a new tab. And there is also a button to create a new plan.
- heart rate zones: contains personal zones if they are already calculated, or a calculator and some information, why it is important to follow the zone during training
- and a page with personal information: in order to change name, password (will be available in menu under the icon of account, together with 'log out' button)

So, user:
- clicks on the button to create a plan and is redirected to the page with input form
- enters the necessary data
- and after a submission goes back to the page with the list of plans, where the new plan is already added.
On the page of the plan will be a calendar with all of the trainings, and user can click on each training to see details, to tick trainings as done or to move it on another day.

That's how I see it. I'm open to your comments and follow-up questions.

**Comment by BTBTravis** [comment]
Alright the idea is clear enough with me for us to get started. 

I've created a [sitemap](https://octopus.do/br3o3fb90lk) with my understanding of the project. DM me for an edit link. 

<img width="690" alt="Screenshot 2020-05-26 at 08 55 04" src="https://user-images.githubusercontent.com/13404719/82869503-aabc4a80-9f2e-11ea-998b-edd30d6c898e.png">

Lets take the next steps. I will create follow up issues. I approve of your idea so please update the `README.md` of this repo with your information in a new pull request.

**Comment by khomtali** [comment]
Done, see #4 

Can I open a new issue with discussion of APIs?

**Comment by BTBTravis** [comment]
yes please do open an issue. as you have updated readme and we have general idea closing this issue
