### ISSUE TITLE
auth module location

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_khomtali#12]
Hey @khomtali in regard to the file https://github.com/redi-js-teachers/js_sprint_2020_final_project_khomtali/blob/master/src/components/auth/index.js I feel it is in the wrong location. You have a nice structure going with `/components`, `/models`, and `/contexts`. 

Where do you think the auth module should go? Its not a react component so maybe not in the `/components` folder. Also it is used by both components and contexts. 

Perhaps just as /auth.js in root dir or?

Also in regard to organizing your components. I find it easy to follow this pattern:
- if a component is of a single domain and a single file its just `/components/SignupForm.js`
- if the component is more complex then do a folder component with an index.js ex `/components/SignupForm/index.js`, `/components/SignupForm/SignupErrorBucket.js`, `/components/SignupForm/SignFrom/SuccessOverlay.js`

**Comment by khomtali** [comment]
Hi @BTBTravis 
good point about the file location, thank you. I placed it in that directory, because now it is used only in files of that dir - by `Signup.js` and `UserProvider.js`. I can move it to the root dir, but what if there will be a lot of such files? How can I name a new dir? `configurations` or what else? could I also move `constants.js` to this new dir?

About 2nd point of organising `/components` dir, I understand it as `index.js` is included all other 'sub'-components in this dir. Am I right?

I replace and rename all the necessary files as you wrote, instead of may be `/auth`, because that is not the final structure of this component. Later I add there `index.js` file.

**Comment by BTBTravis** [comment]
> "About 2nd point of organizing /components dir, I understand it as index.js is included all other 'sub'-components in this dir. Am I right?"

So the only special thing about `/Footer/index.js` is that it can be imported like
`import CoolFooter from './Footer'` 
instead of 
`import CoolFooter from './Footer/index.js'`

**Comment by BTBTravis** [comment]
solved in #13
